# 机器人绑定群号 暂时仅支持一个群
receive-group:
  - 1042672065
  - 615313559

# 禁止QQ群执行的命令 查询命令容易刷屏被限制,建议禁止
prohibition-execution:
  - help
  - stop
  - status
  - say
  - list

# 显示服务器玩家聊天消息在QQ群
show-server-player-chat: true

# 服务器出入提示 & 支持Tips
join-quit-tips:
  enable: true
  join: §b{name} 进入了服务器
  exit: §b{name} 退出了服务器

# 群聊天显示格式 & 需要依赖Tips 插件 支持Tips注入的变量 & 使用需要开启服务器消息聊天显示
group-tips:
  enable: false
  format: §7[§e{levelName}§7] §7[§a{ms}§7] §b{name} §7>> §r{msg}

