name: mirai-nukkit-bot
main: top.zixuan007.bot.BotPlugin
version: "1.1.0"
api: [ "1.0.9" ]
load: POSTWORLD
author: "zixuan007"
depend: [ MiraiMC ]

commands:
  bindqq:
    description: "绑定服务器玩家的QQ账号"
    usage: "/bindqq [QQ账号] >> 绑定游戏账号&QQ账号"
    permission: botplugin.command.user

permissions:
  botplugin.command.user:
    description: "绑定服务器玩家的QQ账号"
    default: true
