on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # mirai-nukkit-bot-SNAPSHOT.jar
      - name: Upload a Build Artifact - mirai-nukkit-bot
        uses: actions/upload-artifact@v2.3.1
        with:
          name: "mirai-nukkit-bot-SNAPSHOT.jar"
          path: mirai-nukkit-bot/target/mirai-nukkit-bot-SNAPSHOT.jar
